# Generated by Django 4.0.4 on 2022-04-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(default='', max_length=255)),
                ('cat_desc', models.CharField(default='', max_length=1000)),
                ('cat_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
