# Generated by Django 3.2.8 on 2022-04-16 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumapp', '0007_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='ques_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='ques_parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forumapp.categories'),
        ),
        migrations.AddField(
            model_name='question',
            name='ques_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='ques_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='ques_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
