# Generated by Django 4.0.4 on 2022-04-17 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forumapp', '0008_auto_20220416_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_img', models.ImageField(default='static/IMG/user.png', upload_to='user_img/images')),
            ],
        ),
    ]
