# Generated by Django 4.0.4 on 2022-04-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0011_alter_user_details_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='_user',
        ),
        migrations.AddField(
            model_name='user_details',
            name='user',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
