# Generated by Django 4.0.4 on 2022-04-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0013_alter_user_details_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_img',
            field=models.ImageField(default='IMG/user.png', upload_to='user_img/images'),
        ),
    ]
