# Generated by Django 4.0.4 on 2022-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0015_remove_user_details_user_user_details__user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_user_img',
            field=models.ImageField(default='IMG?user.png', upload_to='ques_img/images'),
        ),
    ]
