# Generated by Django 4.0.4 on 2022-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0016_question_ques_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_user_img',
            field=models.ImageField(default='IMG/user.png', upload_to='ques_img/images'),
        ),
    ]
