# Generated by Django 4.0.4 on 2022-04-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0017_alter_question_ques_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ques_user_img',
        ),
    ]
