# Generated by Django 4.0.4 on 2022-04-21 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0019_question_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_reply',
            name='reply_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
