# Generated by Django 4.0.4 on 2022-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0020_question_reply_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_reply',
            name='reply_category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
