# Generated by Django 4.0.4 on 2022-04-23 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forumapp', '0021_question_reply_reply_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Unknown', max_length=250)),
                ('email', models.EmailField(default='', max_length=125)),
                ('phone', models.IntegerField()),
                ('query', models.TextField(default='')),
            ],
        ),
    ]
